export default [
    {
        files: ['**/*.js'],
        ignores: [
            'node_modules/**',
            'service-worker.js',
            'image-worker.js',
            'tests/**',
            'eslint.config.js',
            'vitest.config.js'
        ],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'script',
            globals: {
                // Browser globals
                window: 'readonly',
                document: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                fetch: 'readonly',
                console: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                clearTimeout: 'readonly',
                clearInterval: 'readonly',
                requestAnimationFrame: 'readonly',
                URL: 'readonly',
                Blob: 'readonly',
                File: 'readonly',
                FileReader: 'readonly',
                FormData: 'readonly',
                AbortController: 'readonly',
                OffscreenCanvas: 'readonly',
                createImageBitmap: 'readonly',
                indexedDB: 'readonly',
                Image: 'readonly',
                HTMLElement: 'readonly',
                CustomEvent: 'readonly',
                MutationObserver: 'readonly',
                IntersectionObserver: 'readonly',
                ResizeObserver: 'readonly',
                navigator: 'readonly',
                location: 'readonly',
                history: 'readonly',
                performance: 'readonly',
                // Project globals
                CONFIG: 'readonly',
                ngSupabase: 'readonly',
                events: 'readonly',
                api: 'readonly',
                i18n: 'readonly',
                SharedUI: 'readonly',
                SharedHistory: 'readonly',
                SharedFavorites: 'readonly',
                SharedUpload: 'readonly',
                SharedDownload: 'readonly',
                SharedKeyboard: 'readonly',
                SharedCollapsible: 'readonly',
                SharedLanguage: 'readonly',
                SharedTheme: 'readonly',
                SharedRequest: 'readonly',
                SharedHeader: 'readonly',
                SharedLightbox: 'readonly',
                SharedDashboard: 'readonly',
                ReactiveState: 'readonly',
                EventBus: 'readonly',
                APIClient: 'readonly',
                APIError: 'readonly',
                ImageCompressor: 'readonly',
                VirtualScroller: 'readonly',
                LazyLoader: 'readonly',
                RequestDeduplicator: 'readonly',
                ImageStore: 'readonly',
                AccountMenu: 'readonly',
                OnboardingTour: 'readonly'
            }
        },
        rules: {
            // Match existing conventions
            'semi': ['error', 'always'],
            'quotes': ['error', 'single', { avoidEscape: true }],
            'indent': ['error', 4, { SwitchCase: 1 }],
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
            'no-console': 'off',
            'prefer-const': 'warn',
            'eqeqeq': ['warn', 'smart'],
            'curly': ['error', 'multi-line'],
            'brace-style': ['error', '1tbs', { allowSingleLine: true }],
            'comma-dangle': ['error', 'never'],
            'no-trailing-spaces': 'error',
            'eol-last': ['error', 'always']
        }
    }
];
